"""RYS — empirical generated-response CKA connectomes and RYS surgery.

Public re-exports for convenience inside the notebook.
"""

from rys.activations import capture_generated_residual_stream, capture_residual_stream
from rys.addition_data import (
    AdditionDataset,
    AdditionExample,
    digits_to_int,
    make_addition_examples,
    make_addition_splits,
    verify_addition_tensor,
)
from rys.addition_transformer import (
    AdditionBackbone,
    AdditionConfig,
    AdditionTransformer,
)
from rys.analytical_fk import (
    FkPrior,
    compare_prior_to_empirical,
    gaussian_fk_prior,
    instantiate_single_block,
    predict_rho_Q_apriori,
    predict_rys_windows,
    qwen_layer_type_table,
    resolve_device,
    silu_moments_under_gaussian,
    simulate_block_activations,
)
from rys.cka import cka_matrix, cka_matrix_bootstrap
from rys.coloring_data import (
    ColoringDataset,
    ColoringExample,
    coloring_is_valid,
    make_coloring_examples,
    make_coloring_splits,
    soft_coloring_loss,
    verify_coloring_tensor,
)
from rys.coloring_message_passing import (
    ColoringBackbone,
    ColoringMessagePassingModel,
    ColoringMPConfig,
    ColoringRound,
)
from rys.data import csqa_prompts, gsm8k_prompts, mmlu_prompts
from rys.gsm8k_mc import (
    build_distractors,
    load_pythia,
    make_gsm8k_mc,
    mc_accuracy,
    parse_gold,
    prepare_mc_batches,
    score_mc,
    score_prepared,
)
from rys.guesstimation import (
    calculate_score,
    generate_numbers,
    make_guesstimation_questions,
    parse_number,
    probe_score,
    score_estimates,
)
from rys.modules import change_points, leiden_communities, plateau_metric
from rys.nqueens_data import (
    QueensDataset,
    QueensExample,
    board_is_valid,
    make_queens_examples,
    make_queens_splits,
    soft_nqueens_loss,
    verify_boards_tensor,
)
from rys.nqueens_message_passing import (
    QueensBackbone,
    QueensMessagePassingModel,
    QueensMPConfig,
    QueensRound,
)
from rys.plots import connectome_heatmap, delta_heatmap, panel
from rys.residual_force import (
    amplification_long,
    predict_cka_under_rys,
    residual_force_long,
    residual_force_matrices,
)
from rys.sat_data import (
    ClauseAssignmentDataset,
    NBucketBatchSampler,
    SatAssignmentDataset,
    SatAssignmentExample,
    SatDataset,
    SatExample,
    assignment_satisfies_formula,
    collate_clause_assignment,
    encode_clause_tensor,
    encode_formula,
    encode_formula_assignment_factorized,
    encode_formula_factorized,
    factorized_assignment_sequence_length,
    factorized_sequence_length,
    first_satisfying_assignment,
    make_sat_assignment_examples,
    make_sat_assignment_splits,
    make_sat_examples,
    make_sat_splits,
    multisample_validity,
    soft_sat_loss,
    verify_assignment_tensor,
)
from rys.sat_message_passing import (
    MessagePassingConfig,
    MessagePassingRound,
    MessagePassingSatModel,
)
from rys.sorted_translation_data import (
    SortedExample,
    SortedTranslationDataset,
    make_sorted_examples,
    make_sorted_splits,
    sortedness,
    verify_sorted_tensor,
)
from rys.sorted_translation_transformer import (
    RoPESelfAttentionRound,
    SortedTranslationBackbone,
    SortedTranslationConfig,
    SortedTranslationTransformer,
)
from rys.surgery import apply_rys
from rys.tensor_activations import capture_tensor_residual_stream
from rys.theory_validation import (
    block_jacobian_sigma_max,
    junction_mismatch,
    rho_phi_table,
    rys_amplification_summary,
    theory_fit,
)
from rys.tiny_transformer import (
    FactorizedAssignmentTransformerConfig,
    FactorizedCNFAssignmentTransformer,
    FactorizedCNFSatTransformer,
    FactorizedCNFTransformerConfig,
    TinySatTransformer,
    TinyTransformerConfig,
)

__all__ = [
    "AdditionBackbone",
    "AdditionConfig",
    "AdditionDataset",
    "AdditionExample",
    "AdditionTransformer",
    "digits_to_int",
    "make_addition_examples",
    "make_addition_splits",
    "verify_addition_tensor",
    "FkPrior",
    "ClauseAssignmentDataset",
    "NBucketBatchSampler",
    "collate_clause_assignment",
    "SatAssignmentDataset",
    "SatAssignmentExample",
    "SatDataset",
    "SatExample",
    "ColoringBackbone",
    "ColoringDataset",
    "ColoringExample",
    "ColoringMPConfig",
    "ColoringMessagePassingModel",
    "ColoringRound",
    "coloring_is_valid",
    "make_coloring_examples",
    "make_coloring_splits",
    "soft_coloring_loss",
    "verify_coloring_tensor",
    "FactorizedAssignmentTransformerConfig",
    "FactorizedCNFAssignmentTransformer",
    "FactorizedCNFSatTransformer",
    "FactorizedCNFTransformerConfig",
    "MessagePassingConfig",
    "MessagePassingRound",
    "MessagePassingSatModel",
    "QueensBackbone",
    "QueensDataset",
    "QueensExample",
    "QueensMPConfig",
    "QueensMessagePassingModel",
    "QueensRound",
    "board_is_valid",
    "make_queens_examples",
    "make_queens_splits",
    "soft_nqueens_loss",
    "verify_boards_tensor",
    "RoPESelfAttentionRound",
    "SortedExample",
    "SortedTranslationBackbone",
    "SortedTranslationConfig",
    "SortedTranslationDataset",
    "SortedTranslationTransformer",
    "make_sorted_examples",
    "make_sorted_splits",
    "sortedness",
    "verify_sorted_tensor",
    "TinySatTransformer",
    "TinyTransformerConfig",
    "amplification_long",
    "apply_rys",
    "block_jacobian_sigma_max",
    "junction_mismatch",
    "rho_phi_table",
    "rys_amplification_summary",
    "theory_fit",
    "capture_generated_residual_stream",
    "capture_residual_stream",
    "capture_tensor_residual_stream",
    "change_points",
    "cka_matrix",
    "cka_matrix_bootstrap",
    "compare_prior_to_empirical",
    "connectome_heatmap",
    "csqa_prompts",
    "delta_heatmap",
    "assignment_satisfies_formula",
    "build_distractors",
    "load_pythia",
    "make_gsm8k_mc",
    "mc_accuracy",
    "parse_gold",
    "prepare_mc_batches",
    "score_mc",
    "score_prepared",
    "calculate_score",
    "generate_numbers",
    "make_guesstimation_questions",
    "parse_number",
    "probe_score",
    "score_estimates",
    "encode_clause_tensor",
    "encode_formula",
    "encode_formula_assignment_factorized",
    "encode_formula_factorized",
    "factorized_assignment_sequence_length",
    "factorized_sequence_length",
    "first_satisfying_assignment",
    "gaussian_fk_prior",
    "gsm8k_prompts",
    "instantiate_single_block",
    "leiden_communities",
    "make_sat_examples",
    "make_sat_assignment_examples",
    "make_sat_assignment_splits",
    "make_sat_splits",
    "mmlu_prompts",
    "multisample_validity",
    "panel",
    "plateau_metric",
    "predict_cka_under_rys",
    "predict_rho_Q_apriori",
    "predict_rys_windows",
    "qwen_layer_type_table",
    "residual_force_long",
    "residual_force_matrices",
    "resolve_device",
    "silu_moments_under_gaussian",
    "simulate_block_activations",
    "soft_sat_loss",
    "verify_assignment_tensor",
]
